#!/bin/sh

# Text Reset
NC="\033[0m"

# Regular Colors
black="\033[0;30m"
red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
blue="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
white="\033[0;37m"

# High Intensity
iwhite="\033[0;97m"

# split arguments for this script and the rest for tail
color="$iwhite"
tail_args=$@
if [ $# -eq 1 ]; then
    if [ "$1" == "-h" ]; then
        echo "Usage: ctail [-p <color name>] [TAIL OPTIONS]... [FILE]..."
        exit 0
    fi
elif [ $# -gt 1 ]; then
    if [ "$1" == "-p" ]; then
        case "$2" in
            black) color="$black" ;;
            red) color="$red" ;;
            green) color="$green" ;;
            yellow) color="$yellow" ;;
            blue) color="$blue" ;;
            purple) color="$purple" ;;
            cyan) color="$cyan" ;;
            white) color="$white" ;;
            *) color="$iwhite"
        esac
        tail_args="${@:3}"
    fi
fi

# tail it & color it
tail $tail_args | while read line; do
    printf "${color}$line${NC}\n";
done
